name: Gradle Build Workflow

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      # 카프카 서비스 추가
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - 2181:2181
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      kafka:
        image: confluentinc/cp-kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradle
        working-directory: ./backend
        run: chmod +x ./gradlew

      - name: Set MongoDB URI
        run: echo "TEST_MONGO_DB_URI=${{ secrets.TEST_MONGO_DB_URI }}" >> $GITHUB_ENV

      - name: Build with Gradle
        working-directory: ./backend
        run: ./gradlew clean build --stacktrace --info

      - name: Start Redis and configure
        run: |
          docker exec $(docker ps -q --filter "ancestor=redis:latest") redis-cli CONFIG SET notify-keyspace-events Ex
          docker exec $(docker ps -q --filter "ancestor=redis:latest") redis-cli CONFIG GET notify-keyspace-events

      - name: Create file storage directory for tests
        working-directory: ./backend
        run: |
          mkdir -p testUploads
          chmod 777 testUploads
